# Generated by Django 5.2.5 on 2025-11-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_time',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated time in minutes for order preparation', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='preparation_time',
            field=models.PositiveIntegerField(blank=True, help_text='Time in minutes', null=True),
        ),
    ]
