# Generated by Django 5.2.5 on 2025-11-13 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_delete_orders_order_estimated_time_alter_order_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='estimated_time',
        ),
        migrations.AddField(
            model_name='order',
            name='order_code',
            field=models.CharField(blank=True, editable=False, max_length=6, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='product_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
